table 'Catálogo de ENTIDADES'
	lineageTag: 21a5ac9b-f0b2-486a-b880-1854d89c4904

	column CLAVE_ENTIDAD
		dataType: int64
		formatString: 0
		lineageTag: c8c3ac42-b9ea-4dba-8d8a-d13f09f6073c
		summarizeBy: none
		sourceColumn: CLAVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column ENTIDAD_FEDERATIVA
		dataType: string
		lineageTag: b5166881-5950-48b9-99b2-99789e490a31
		summarizeBy: none
		sourceColumn: ENTIDAD_FEDERATIVA

		annotation SummarizationSetBy = Automatic

	column ABREVIATURA
		dataType: string
		lineageTag: 11583b6d-fbfb-4dcc-9484-33fb1351150a
		summarizeBy: none
		sourceColumn: ABREVIATURA

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo de ENTIDADES' = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Catálogo de ENTIDADES", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"CLAVE_ENTIDAD", Int64.Type}, {"ENTIDAD_FEDERATIVA", type text}, {"ABREVIATURA", type text}}, "es")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

