table 'Catálogo ORIGEN'
	lineageTag: 4bce6085-ef33-40b0-8dcc-f8364e38db00

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: a37cb2fb-7234-42c1-839b-60ec9984130c
		summarizeBy: sum
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 4161ca26-ba57-4cbf-86cd-f96b0f391c52
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo ORIGEN' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo ORIGEN_Sheet" = Origen{[Item="Catálogo ORIGEN",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo ORIGEN_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

