table 'Catálogo TIPO_PACIENTE'
	lineageTag: 21165fc7-00e8-448f-aebc-9d6a3440a4a2

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: 296fc7e9-5df0-4e6c-a20e-95a7f7f04731
		summarizeBy: none
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: c9e86a60-81b7-4af0-bec5-97dc6b891d05
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo TIPO_PACIENTE' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo TIPO_PACIENTE_Sheet" = Origen{[Item="Catálogo TIPO_PACIENTE",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo TIPO_PACIENTE_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

