table 'Catálogo RESULTADO_PCR'
	lineageTag: f4546892-7b32-460c-bc23-e30043671e60

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: 2dd96f30-4f38-4aa4-9f40-ee72c5d96418
		summarizeBy: sum
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 9261a467-8113-409d-9572-a8e903f73448
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo RESULTADO_PCR' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo RESULTADO_PCR_Sheet" = Origen{[Item="Catálogo RESULTADO_PCR",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo RESULTADO_PCR_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}, {"Column3", type any}, {"Column4", type any}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Column3", "Column4"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

