table 'Catálogo NACIONALIDAD'
	lineageTag: 0c81c6cd-497e-4383-a817-c47a03856178

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: 99655da8-9fa4-41da-997c-c902046a77d6
		summarizeBy: none
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 47b26b35-1226-42d3-9300-e584a10ab180
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo NACIONALIDAD' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo NACIONALIDAD_Sheet" = Origen{[Item="Catálogo NACIONALIDAD",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo NACIONALIDAD_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

