table 'Catálogo RESULTADO_ANTIGENO'
	lineageTag: 7a29fb9f-331f-4b56-a416-c315787efaf8

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: 77fef7f0-1530-47a3-94c3-04174294cc09
		summarizeBy: sum
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 97fa4036-5a62-4015-b223-01ed8f2cd804
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo RESULTADO_ANTIGENO' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo RESULTADO_ANTIGENO_Sheet" = Origen{[Item="Catálogo RESULTADO_ANTIGENO",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo RESULTADO_ANTIGENO_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

