table 'Catálogo SEXO'
	lineageTag: 5f017ee4-dcf2-4bcb-93ee-f2f2ba954e5b

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: e2dd0b78-75c9-4975-b673-47a1c5cdab01
		summarizeBy: none
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 372ffa27-7587-4205-bd93-7e86b38317ac
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo SEXO' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo SEXO_Sheet" = Origen{[Item="Catálogo SEXO",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo SEXO_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

