table 'Catálogo MUNICIPIOS'
	lineageTag: bec81287-6c6b-4fdd-9333-c29f518ee7ac

	column CLAVE_ENTIDAD
		dataType: int64
		formatString: 0
		lineageTag: 6185f685-220d-44ad-82c9-0695ee03dd8c
		summarizeBy: sum
		sourceColumn: CLAVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column CLAVE_MUNICIPIO
		dataType: int64
		formatString: 0
		lineageTag: 361a9ace-fe30-43d7-bb16-81f826a1e5b7
		summarizeBy: sum
		sourceColumn: CLAVE_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column MUNICIPIO
		dataType: string
		lineageTag: 0f961a6f-27db-4191-8754-d59bbb8c1a32
		summarizeBy: none
		sourceColumn: MUNICIPIO

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo MUNICIPIOS' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo MUNICIPIOS_Sheet" = Origen{[Item="Catálogo MUNICIPIOS",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo MUNICIPIOS_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE_ENTIDAD", Int64.Type}, {"CLAVE_MUNICIPIO", Int64.Type}, {"MUNICIPIO", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

