table 'Catálogo de ENTIDADES'
	lineageTag: 6ef180d5-b36d-4f0e-8359-5a2921e6852b

	column CLAVE_ENTIDAD
		dataType: int64
		formatString: 0
		lineageTag: fade3ecd-ba9b-430a-ba51-4798f97566bd
		summarizeBy: none
		sourceColumn: CLAVE_ENTIDAD

		annotation SummarizationSetBy = Automatic

	column ENTIDAD_FEDERATIVA
		dataType: string
		lineageTag: e08e0e22-6a97-4de0-bf74-d3cfbd14078e
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: ENTIDAD_FEDERATIVA

		annotation SummarizationSetBy = Automatic

	column ABREVIATURA
		dataType: string
		lineageTag: 7ec6087e-901f-4d26-b464-f9e4376cea2e
		summarizeBy: none
		sourceColumn: ABREVIATURA

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo de ENTIDADES' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				    #"Catálogo de ENTIDADES_Sheet" = Origen{[Item="Catálogo de ENTIDADES",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Catálogo de ENTIDADES_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"CLAVE_ENTIDAD", Int64.Type}, {"ENTIDAD_FEDERATIVA", type text}, {"ABREVIATURA", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

