table 'Catálogo SEXO'
	lineageTag: 9355b8f5-f496-4400-bc69-099967133470

	column CLAVE
		dataType: int64
		formatString: 0
		lineageTag: 84337563-0149-4100-a6b0-c329187d5ace
		summarizeBy: none
		sourceColumn: CLAVE

		annotation SummarizationSetBy = Automatic

	column DESCRIPCIÓN
		dataType: string
		lineageTag: 30d4f852-65a0-453d-80a4-af58320618c7
		summarizeBy: none
		sourceColumn: DESCRIPCIÓN

		annotation SummarizationSetBy = Automatic

	partition 'Catálogo SEXO' = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents("C:\Users\jurie\Documents\Data-Analysis-Covid19-Mexico\DICCIONARIOS\240708 Catalogos.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Catálogo SEXO", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"CLAVE", Int64.Type}, {"DESCRIPCIÓN", type text}}, "es")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

