table fact_covid
	lineageTag: 36310c93-73a1-4fb3-b926-d6de7ca875c5

	column FECHA_ACTUALIZACION
		dataType: string
		lineageTag: a460a5ba-4ef1-49a9-8a29-52bdb0d35d62
		summarizeBy: none
		sourceColumn: FECHA_ACTUALIZACION

		annotation SummarizationSetBy = Automatic

	column ID_REGISTRO
		dataType: string
		lineageTag: b4a69ce9-8f0e-4b7a-bbc0-34aabd7c2bfc
		summarizeBy: none
		sourceColumn: ID_REGISTRO

		annotation SummarizationSetBy = Automatic

	column FECHA_INGRESO
		dataType: dateTime
		formatString: General Date
		lineageTag: 04d33bf8-7a00-4f50-9f68-a5b45875c14f
		summarizeBy: none
		sourceColumn: FECHA_INGRESO

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column FECHA_SINTOMAS
		dataType: string
		lineageTag: 1b76b7a4-74be-496c-a755-e1055153154b
		summarizeBy: none
		sourceColumn: FECHA_SINTOMAS

		annotation SummarizationSetBy = Automatic

	column FECHA_DEF
		dataType: string
		lineageTag: cb69f6f8-c3d7-41c3-9b74-77aa2e0d6f8f
		summarizeBy: none
		sourceColumn: FECHA_DEF

		annotation SummarizationSetBy = Automatic

	column ID_DIM_GEOGRAFICO_INFORMACION_PACIENTE
		dataType: int64
		formatString: 0
		lineageTag: 24120c7c-8f85-447c-b3b8-4b21f39c4e5a
		summarizeBy: none
		sourceColumn: ID_DIM_GEOGRAFICO_INFORMACION_PACIENTE

		annotation SummarizationSetBy = Automatic

	column ID_DIM_GEOGRAFICO_RESIDENCIA
		dataType: int64
		formatString: 0
		lineageTag: ec5a9392-892e-4e4f-acde-917e4ee9108d
		summarizeBy: none
		sourceColumn: ID_DIM_GEOGRAFICO_RESIDENCIA

		annotation SummarizationSetBy = Automatic

	column ID_DIM_GEOGRAFICO_NACIONALIDAD
		dataType: int64
		formatString: 0
		lineageTag: 293a5ab1-b97a-407a-8b54-abe17005e286
		summarizeBy: none
		sourceColumn: ID_DIM_GEOGRAFICO_NACIONALIDAD

		annotation SummarizationSetBy = Automatic

	column ID_DIM_DESCRIPCION_DEL_PACIENTE
		dataType: int64
		formatString: 0
		lineageTag: e767f2bf-cbed-4085-b29e-49bd012af275
		summarizeBy: none
		sourceColumn: ID_DIM_DESCRIPCION_DEL_PACIENTE

		annotation SummarizationSetBy = Automatic

	column ID_DIM_INDIGENA
		dataType: int64
		formatString: 0
		lineageTag: 86ca0701-7263-4b63-ad53-7671a6a4ac37
		summarizeBy: none
		sourceColumn: ID_DIM_INDIGENA

		annotation SummarizationSetBy = Automatic

	column ID_DIM_COMORBILIDADES_RESPIRATORIAS
		dataType: int64
		formatString: 0
		lineageTag: 300e711e-7fbb-4801-90ea-91b2f1ffe08c
		summarizeBy: none
		sourceColumn: ID_DIM_COMORBILIDADES_RESPIRATORIAS

		annotation SummarizationSetBy = Automatic

	column ID_DIM_COMORBILIDADES_DE_PRESION
		dataType: int64
		formatString: 0
		lineageTag: d719e845-fe4b-475b-b1f5-dcda6aa627cd
		summarizeBy: none
		sourceColumn: ID_DIM_COMORBILIDADES_DE_PRESION

		annotation SummarizationSetBy = Automatic

	column ID_DIM_OTRAS_CARACTERISTICAS_MEDICAS
		dataType: int64
		formatString: 0
		lineageTag: 96843ade-b2dc-48e9-9dd8-6c22874188d2
		summarizeBy: none
		sourceColumn: ID_DIM_OTRAS_CARACTERISTICAS_MEDICAS

		annotation SummarizationSetBy = Automatic

	column ID_DIM_ANTIGENO
		dataType: int64
		formatString: 0
		lineageTag: 01bbc9ba-310e-4f54-81fa-b777907d7e0e
		summarizeBy: none
		sourceColumn: ID_DIM_ANTIGENO

		annotation SummarizationSetBy = Automatic

	column CLASIFICACION_FINAL_COVID
		dataType: int64
		formatString: 0
		lineageTag: eb8ddab3-deb6-43b3-9ed9-502f0b64e755
		summarizeBy: count
		sourceColumn: CLASIFICACION_FINAL_COVID

		annotation SummarizationSetBy = Automatic

	column CLASIFICACION_FINAL_FLU
		dataType: int64
		formatString: 0
		lineageTag: 1e15b2d9-7252-4da0-992a-6a54bc43b5a5
		summarizeBy: sum
		sourceColumn: CLASIFICACION_FINAL_FLU

		annotation SummarizationSetBy = Automatic

	column ID_DIM_UBICACION_DE_LABORATORIO
		dataType: int64
		formatString: 0
		lineageTag: e516420b-aabd-4bf4-b69b-3c9265a628c4
		summarizeBy: none
		sourceColumn: ID_DIM_UBICACION_DE_LABORATORIO

		annotation SummarizationSetBy = Automatic

	column RESULTADO_PCR
		dataType: int64
		formatString: 0
		lineageTag: f5bf67c4-3b2e-4b76-a4ec-da61871d78d8
		summarizeBy: sum
		sourceColumn: RESULTADO_PCR

		annotation SummarizationSetBy = Automatic

	column RESULTADO_PCR_COINFECCION
		dataType: int64
		formatString: 0
		lineageTag: bcb0c75a-21f2-4475-8ef4-88213c0221a1
		summarizeBy: sum
		sourceColumn: RESULTADO_PCR_COINFECCION

		annotation SummarizationSetBy = Automatic

	column ID_DIM_DATOS_DE_LABORATORIO
		dataType: int64
		formatString: 0
		lineageTag: c85f83ee-0708-4bbf-885a-1205243d8f8f
		summarizeBy: none
		sourceColumn: ID_DIM_DATOS_DE_LABORATORIO

		annotation SummarizationSetBy = Automatic

	column FECHA_INGRESO_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: de93f6e6-82a8-4da3-bdae-2e5e9144474c
		summarizeBy: none
		sourceColumn: FECHA_INGRESO_DATE

		variation Variación
			isDefault
			relationship: ff7b4a98-e424-402d-bccd-ccdc84274b11
			defaultHierarchy: LocalDateTable_ac42842a-15cf-4563-b6d8-464073d38bb5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FECHA_SINTOMAS_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: e91aec16-1468-4776-ab34-26358f44e6df
		summarizeBy: none
		sourceColumn: FECHA_SINTOMAS_DATE

		variation Variación
			isDefault
			relationship: 5c0166e5-4f7d-4de4-a38f-50eb5ed866eb
			defaultHierarchy: LocalDateTable_e196a8a3-3cab-4355-88a1-99777be175bf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FECHA_DEF_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96540de6-b23a-4c0e-a2ae-dce78f2cfa37
		summarizeBy: none
		sourceColumn: FECHA_DEF_DATE

		variation Variación
			isDefault
			relationship: 2e6299e0-64ac-4792-bb8b-d90976fe3fb3
			defaultHierarchy: LocalDateTable_9fb96b51-d13d-4406-ab7e-be7832256da4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_covid = m
		mode: import
		source =
				let
				    Origen = Odbc.DataSource("dsn=DSN_Covid_Lakehouse", [HierarchicalNavigation=true]),
				    covid_lakehouse_Database = Origen{[Name="covid_lakehouse",Kind="Database"]}[Data],
				    main_Schema = covid_lakehouse_Database{[Name="main",Kind="Schema"]}[Data],
				    fact_covid_View = main_Schema{[Name="fact_covid",Kind="View"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(fact_covid_View,{"INTUBADO", "NEUMONIA", "EDAD", "NACIONALIDAD", "EMBARAZO", "HABLA_LENGUA_INDIG", "INDIGENA", "DIABETES", "EPOC", "ASMA", "INMUSUPR", "HIPERTENSION", "OTRA_COM", "CARDIOVASCULAR", "OBESIDAD", "RENAL_CRONICA", "TABAQUISMO", "OTRO_CASO", "TOMA_MUESTRA_LAB", "RESULTADO_LAB", "TOMA_MUESTRA_ANTIGENO", "RESULTADO_ANTIGENO", "CLASIFICACION_FINAL", "MIGRANTE", "PAIS_NACIONALIDAD", "PAIS_ORIGEN", "UCI", "ORIGEN", "SECTOR", "ENTIDAD_UM", "SEXO", "ENTIDAD_NAC", "ENTIDAD_RES", "MUNICIPIO_RES", "TIPO_PACIENTE", "month", "year"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

